title = "The Archive"
theme = "private"
locale = "en"
baseURL = "https://blog.m0n5t3r.com/"

pagination.pagerSize = 20

[params]
author = "Ji-Hoon Kim"
info = "Mathematician and Software Engineer"
description = "The archive that records everything"
keywords = "blog,personal,mathematician,software-engineer,developer"
avatarURL = "images/avatar.png"

faviconSVG = "images/favicon/favicon.svg"
favicon_32 = "images/favicon/favicon-32x32.png"
favicon_16 = "images/favicon/favicon-16x16.png"
touchIcon = "images/favicon/apple-touch-icon.png"

since = 2023
katex = true

[[params.book_groups]]
title = "그로스 해킹: 데이터로 증명하는 성장의 공식"
prefix = "growth-hacking"

[[params.book_groups]]
title = "그림과 실습으로 배우는 쿠버네티스 입문"
prefix = "bbf-k8s"

[[params.book_groups]]
title = "코틀린 아카데미: 핵심편"
prefix = "kotlin-essentials"

[[params.book_groups]]
title = "코틀린 코루틴 (Kotlin Coroutines: Deep Dive)"
prefix = "kotlin-coroutines"

[[params.book_groups]]
title = "클린 아키텍처: 소프트웨어 구조와 설계의 원칙"
prefix = "clean-architecture"

[params.theme_config]
date_format = "2006-01-02"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Projects"
weight = 4
url = "projects/"

[[menu.main]]
name = "Books"
weight = 5
url = "books/"

[[menu.main]]
name = "About"
weight = 6
url = "about/"

[[menu.footer]]
name = "GitHub"
url = "https://github.com/bossm0n5t3r"
weight = 1

[[menu.footer]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/zhoon-kim/"
weight = 2


[markup.highlight]
anchorLineNos = true
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = 'catppuccin-mocha'
tabWidth = 4

[markup]
[markup.goldmark]
renderer.unsafe = true
[markup.goldmark.extensions]
footnote = true
