# This file is used only when developing the theme as a standalone Hugo site.
# The blog itself is configured by ../../config.toml.

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
