name = 'Private'
license = 'MIT'
licenselink = 'https://github.com/bossm0n5t3r/blog/blob/master/themes/private/LICENSE'
description = 'An original Hugo theme created for The Archive'
homepage = 'https://github.com/bossm0n5t3r/blog'
tags = ['blog', 'personal', 'responsive']
features = ['responsive', 'syntax-highlighting', 'math']

[author]
name = 'Ji-Hoon Kim'
homepage = 'https://github.com/bossm0n5t3r'
